#Amazon-Books-Deploy Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-books
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-books
  template:
    metadata:
      labels:
        app: amazon-books
    spec:
      containers:
      - name: amazon-books-container
        image: nginx:latest
        ports:
        - containerPort: 80